{
  device.build = "FmK7W5o44OWWB0mBXr2xjSUn+4Q=";
  device.core.disableDefaults = true;
  device.core.locale.defaultLocale = "en_US.UTF-8";
  device.core.locale.supportedLocales = ["en_US.UTF-8/UTF-8" "cs_CZ.UTF-8/UTF-8"];
  device.core.locale.timeZone = "Europe/Prague";
  device.core.network.domain = "clients.joka00.dev";
  device.core.network.services.enableAvahi = false;
  device.core.network.services.enableNetworkManager = false;
  device.core.network.services.enableResolved = false;
  device.core.securityRules.enable = true;
  device.core.shells.fish.enable = true;
  device.core.shells.zsh.enable = false;
  device.core.storage.enablePersistence = true;
  device.core.storage.swapFile.enable = true;
  device.core.storage.swapFile.path = "/swap/swapfile";
  device.core.storage.swapFile.size = 8;
  device.desktop.gamemode.enable = false;
  device.desktop.wayland.desktopManager.gnome.enable = false;
  device.desktop.wayland.desktopManager.plasma6.enable = false;
  device.desktop.wayland.displayManager.gdm.enable = false;
  device.desktop.wayland.windowManager.hyprland.enable = false;
  device.desktop.wayland.windowManager.sway.enable = false;
  device.server.homelab.enable = true;
  device.server.homelab.blocky.enable = true;
  device.server.homelab.homeassistant.enable = true;
  device.server.homelab.mosquitto.enable = true;
  device.server.homelab.zigbee2mqtt.enable = true;
  device.server.services.frigate.enable = true;
  device.server.services.web.nginx.enable = true;
  device.server.services.web.acme.enable = true;
  device.utils.kdeconnect.enable = false;
  device.utils.virtualisation.docker.enable = false;
  device.utils.virtualisation.libvirtd.enable = false;
  device.utils.virtualisation.podman.enable = true;
}
