# GENERATED BY WEB-CONFIG
{
  user.desktop.programs.browsers.brave.enable = true;
  user.desktop.programs.browsers.firefox.enable = true;
  user.desktop.programs.browsers.chromium.enable = true;
  user.desktop.programs.browsers.zen.enable = true;
  user.desktop.programs.browsers.defaultBrowser = "zen";
  user.desktop.programs.editors.vscode.enable = true;
  user.desktop.programs.emulators.alacritty.enable = false;
  user.desktop.programs.emulators.kitty.enable = true;
  user.desktop.programs.emulators.wezterm.enable = false;
  user.desktop.programs.games.lutris.enable = true;
  user.desktop.programs.games.minecraft.enable = true;
  user.desktop.programs.media.mpv.enable = true;
  user.desktop.programs.productivity.zathura.enable = true;
  user.desktop.services.kdeconnect.enable = true;
  user.desktop.services.mako.enable = true;
  user.desktop.services.polkit_agent.enable = true;
  user.desktop.wayland.hyprland.enable = true;
  user.desktop.wayland.hyprland.settings.mod = "SUPER";
  user.desktop.wayland.hyprland.services.anyrun.enable = true;
  user.desktop.wayland.hyprland.services.hypridle.enable = true;
  user.desktop.wayland.hyprland.services.hyprlock.enable = true;
  user.desktop.wayland.hyprland.services.hyprpaper.enable = true;
  user.desktop.wayland.hyprland.plugins.hyprsplit.enable = true;
  user.desktop.wayland.hyprland.plugins.hyprsplit.numberOfWorkspaces = 10;
  user.desktop.wayland.waybar.enable = true;
  user.desktop.gtk.enable = true;
  user.services.media.playerctl.enable = true;
  user.services.system.udiskie.enable = true;
  user.terminal.shell.fish.enable = true;
}
