keys:
  # Users
  - &users:
    - &joka 742FE6210FE60A4AF4A08F1F57F8DBA0EC0126A3
  # Hosts
  - &hosts:
    - &alcedo age1frx3zkwt6qmnnwq5tz2mvylf7ry7ft4vzahs4ajlzcxx3l45950qc0k40x
    - &hirundo age1j9ld6ey62hqd33xkyd2fg9362k6xhm5gavsrpsfalwpcs8smxfdqpk84a2

creation_rules:
  - path_regex: hosts/alcedo/secrets.ya?ml$
    key_groups:
    - age:
      - *alcedo
      pgp:
      - *joka
  - path_regex: hosts/hirundo/secrets.ya?ml$
    key_groups:
    - age:
      - *hirundo
      pgp:
      - *joka
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *alcedo
      - *hirundo
      pgp:
      - *joka
