keys:
  # Users
  - &users:
    - &joka 7A0AF5B9AABC2CC6
  # Hosts
  - &hosts:
    - &alcedo age1frx3zkwt6qmnnwq5tz2mvylf7ry7ft4vzahs4ajlzcxx3l45950qc0k40x
    - &hirundo age1gghr2ul49papjh9c6cdrh209p29nf64wnfpjhj34a2jat6tu64pqjx5g7n

creation_rules:
  - path_regex: hosts/hirundo/secrets.ya?ml$
    key_groups:
    - age:
      - *hirundo
      pgp:
      - *joka
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *alcedo
      - *hirundo
      pgp:
      - *joka
