{
  nixpkgs.hostPlatform = "x86_64-linux";
  boot.initrd.availableKernelModules = ["ata_piix" "sr_mod" "uhci_hcd" "virtio_blk" "virtio_pci"];
  device.core.network.static.enable = true;
  device.core.network.static.interfaces."eno2".ipv4.addresses = [
    {
      address = "10.34.70.20";
      prefixLength = 23;
    }
  ];
  device.core.network.static.defaultGateway.address = "10.34.70.62";
  device.core.network.static.defaultGateway.interface = "eno2";
  device.core.network.static.nameservers = ["10.34.70.20" "10.34.70.62"];

# GENERATED BY WEB-CONFIG

  device.type = "server";
  device.virtualized = false;
  device.build = "FmK7W5o44OWWB0mBXr2xjSUn+4Q=";
  device.boot.quietboot.enable = true;
  device.boot.uefi.enable = true;
  device.boot.uefi.secureboot = true;
  device.home.users = ["joka" "joka-ipa"];
  device.core.disableDefaults = true;
  device.core.locale.defaultLocale = "en_US.UTF-8";
  device.core.locale.supportedLocales = ["en_US.UTF-8/UTF-8" "cs_CZ.UTF-8/UTF-8"];
  device.core.locale.timeZone = "Europe/Prague";
  device.core.network.domain = "clients.joka00.dev";
  device.core.network.services.enableAvahi = false;
  device.core.network.services.enableNetworkManager = false;
  device.core.network.services.enableResolved = false;
  device.core.securityRules.enable = true;
  device.core.shells.fish.enable = true;
  device.core.shells.zsh.enable = false;
  device.core.storage.enablePersistence = true;
  device.core.storage.otherDrives = [];
  device.core.storage.swapFile.enable = true;
  device.core.storage.swapFile.path = "/swap/swapfile";
  device.core.storage.swapFile.size = 8;
  device.core.storage.systemDrive.encrypted.enable = true;
  device.core.storage.systemDrive.encrypted.path = "/dev/disk/by-partlabel/cryptsystem";
  device.core.storage.systemDrive.name = "system";
  device.core.storage.systemDrive.path = "/dev/disk/by-label/system";
  device.desktop.gamemode.enable = false;
  device.desktop.wayland.desktopManager.gnome.enable = false;
  device.desktop.wayland.desktopManager.plasma6.enable = false;
  device.desktop.wayland.displayManager.gdm.enable = false;
  device.desktop.wayland.displayManager.regreet.enable = false;
  device.desktop.wayland.windowManager.hyprland.enable = false;
  device.desktop.wayland.windowManager.sway.enable = false;
  device.hardware.bluetooth.enable = true;
  device.hardware.bluetooth.enableManager = false;
  device.hardware.cpu.amd.enable = false;
  device.hardware.cpu.intel.enable = true;
  device.hardware.disks.hdd.enable = false;
  device.hardware.disks.ssd.enable = true;
  device.hardware.gpu.amd.enable = false;
  device.hardware.gpu.intel.enable = true;
  device.hardware.gpu.nvidia.enable = false;
  device.hardware.misc.trezor.enable = false;
  device.hardware.misc.xbox.enable = false;
  device.hardware.misc.yubikey.enable = false;
  device.server.homelab.enable = true;
  device.server.homelab.blocky.enable = true;
  device.server.homelab.homeassistant.enable = true;
  device.server.homelab.mosquitto.enable = true;
  device.server.homelab.zigbee2mqtt.enable = true;
  device.server.services.frigate.enable = false;
  device.server.services.web.nginx.enable = true;
  device.server.services.web.acme.enable = true;
  device.utils.kdeconnect.enable = false;
  device.utils.virtualisation.docker.enable = false;
  device.utils.virtualisation.libvirtd.enable = false;
  device.utils.virtualisation.podman.enable = true;
}
