# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    ../common/optional/ephemeral-btrfs.nix
    ../common/optional/encrypted-root.nix
    ../common/optional/swap-file.nix
  ];

  boot.initrd.availableKernelModules = [ "nvme" "ehci_pci" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.resumeDevice = "/dev/disk/by-label/system";
  boot.kernelParams = [ "resume_offset=23078144" ];
  boot.binfmt.emulatedSystems = [ "aarch64-linux" ];
  
  fileSystems."/efi" = {
      device = "/dev/disk/by-label/EFI";
      fsType = "vfat";
    };

  swapDevices = [ 
    { 
    device = "/swap/swapfile"; 
    size = (1024 * 16) + (1024 * 2); 
    } 
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
